/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parqueadero;

import javax.swing.JOptionPane;

/**
 *
 * @author JGabriel
 */
public class Estacion extends javax.swing.JFrame {
    Pila pila = new Pila(10);
    Cola cola = new Cola(10);
    /**
     * Creates new form Parqueadero
     */
    public Estacion() {
        initComponents();
        pila.Modelo();
        cola.Modelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lisPila = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lisCola = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnApilar = new javax.swing.JButton();
        btnDesapilar = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnTamaño = new javax.swing.JButton();
        btnColar = new javax.swing.JButton();
        btnDescolar = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        bntTamañoC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(946, 544));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lisPila.setBackground(new java.awt.Color(255, 255, 255));
        lisPila.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lisPila.setToolTipText("");
        jScrollPane1.setViewportView(lisPila);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 340, 450));

        lisCola.setBackground(new java.awt.Color(255, 255, 255));
        lisCola.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lisCola.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane2.setViewportView(lisCola);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 56, 360, 450));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ESTACIONAMIENTO EN PILA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 350, 28));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("ESTACIONAMIENTO EN COLA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 350, 28));

        btnApilar.setText("APILAR");
        btnApilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApilarActionPerformed(evt);
            }
        });
        getContentPane().add(btnApilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 100, 40));

        btnDesapilar.setText("DESAPILAR");
        btnDesapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesapilarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesapilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 100, 40));

        btnUltimo.setText("ÚLTIMO");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 100, 40));

        btnTamaño.setText("TAMAÑO");
        btnTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamañoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 100, 40));

        btnColar.setText("COLAR");
        btnColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColarActionPerformed(evt);
            }
        });
        getContentPane().add(btnColar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 100, 40));

        btnDescolar.setText("DESCOLAR");
        btnDescolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescolarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 100, 43));

        btnPrimero.setText("PRIMERO");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 100, 40));

        bntTamañoC.setText("TAMAÑO");
        bntTamañoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTamañoCActionPerformed(evt);
            }
        });
        getContentPane().add(bntTamañoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String matricula(){
        String matricula = JOptionPane.showInputDialog(null, "Ingrese Matricula Del Vehiculo");
        if(matricula == null){
            return "";
        }else{
            return matricula;
        }
    }
    private void btnApilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApilarActionPerformed
        String dato = matricula();
        if(!dato.equals("")){
            if(pila.estaLlena()==false){
                pila.apilar(dato);
                pila.Imprimir();
            }else{
                JOptionPane.showMessageDialog(null, "Estacionamiento Lleno");
            } 
        } 
    }//GEN-LAST:event_btnApilarActionPerformed

    private void btnDesapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesapilarActionPerformed
        if(pila.estaVacia()==false){
            pila.desapilar();
            pila.Imprimir();
        }else{
            JOptionPane.showMessageDialog(null, "El Estacionamiento Esta Vacio");
        }
    }//GEN-LAST:event_btnDesapilarActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        JOptionPane.showMessageDialog(null, "El Ultimo Vehiculo Es "+pila.elementoTope());
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamañoActionPerformed
        JOptionPane.showMessageDialog(null, "Estan "+pila.tope+" Vehiculos en la Pila");
    }//GEN-LAST:event_btnTamañoActionPerformed

    private void btnColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColarActionPerformed
        String dato = matricula();
        if(!dato.equals("")){
            if(cola.estaLlena()==false){
                cola.colar(dato);
                cola.Imprimir();
            }else{
                JOptionPane.showMessageDialog(null, "Estacionamiento Lleno");
            } 
        } 
    }//GEN-LAST:event_btnColarActionPerformed

    private void btnDescolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescolarActionPerformed
        if(cola.estaVacia()==false){
            cola.descolar();
            cola.Imprimir();
        }else{
            JOptionPane.showMessageDialog(null, "El Estacionamiento Esta Vacio");
        }
    }//GEN-LAST:event_btnDescolarActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        JOptionPane.showMessageDialog(null, "El Primer Vehiculo ES "+cola.elementoPrimero());
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void bntTamañoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTamañoCActionPerformed
        JOptionPane.showMessageDialog(null, "Estan "+cola.tope+" Vehiculos en la Cola");
    }//GEN-LAST:event_bntTamañoCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntTamañoC;
    private javax.swing.JButton btnApilar;
    private javax.swing.JButton btnColar;
    private javax.swing.JButton btnDesapilar;
    private javax.swing.JButton btnDescolar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnTamaño;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JList<String> lisCola;
    public static javax.swing.JList<String> lisPila;
    // End of variables declaration//GEN-END:variables
}
